# enable-template

log:
  stdout: true
  level: {{ default "info" (env "LOG_LEVEL") }}

persistence:
  defaultStore: mongodb-default
  visibilityStore: mongodb-visibility
  numHistoryShards: {{ default "4" (env "NUM_HISTORY_SHARDS") }}
  datastores:
    mongodb-default:
      customDataStoreConfig:
        name: mongodb
        indexName: temporal
        options:
          type: persistence
      mongodb:
        hosts: ["{{ default "127.0.0.1:27017" (env "MONGODB_SEEDS") }}"]
        user: {{ default "temporal" (env "MONGODB_USER") }}
        password: {{ default "temporal" (env "MONGODB_PASSWORD") }}
        authSource: admin
        databaseName: {{ default "temporal" (env "MONGODB_DATABASE") }}
        replicaSet: {{ default "rs0" (env "MONGODB_REPLICA_SET") }}
        maxConns: 50
    mongodb-visibility:
      customDataStoreConfig:
        name: mongodb
        indexName: temporal_visibility
        options:
          type: visibility
      mongodb:
        hosts: ["{{ default "127.0.0.1:27017" (env "MONGODB_SEEDS") }}"]
        user: {{ default "temporal" (env "MONGODB_USER") }}
        password: {{ default "temporal" (env "MONGODB_PASSWORD") }}
        authSource: admin
        databaseName: {{ default "temporal" (env "MONGODB_DATABASE") }}
        replicaSet: {{ default "rs0" (env "MONGODB_REPLICA_SET") }}
        maxConns: 20

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: {{ default "127.0.0.1" (env "TEMPORAL_BROADCAST_ADDRESS") | quote }}
  pprof:
    port: {{ default "7936" (env "PPROF_PORT") }}

services:
  frontend:
    rpc:
      grpcPort: {{ default "7233" (env "FRONTEND_GRPC_PORT") }}
      membershipPort: {{ default "6933" (env "FRONTEND_MEMBERSHIP_PORT") }}
      bindOnIP: {{ default "127.0.0.1" (env "BIND_ON_IP") | quote }}
      httpPort: {{ default "7243" (env "FRONTEND_HTTP_PORT") }}

  matching:
    rpc:
      grpcPort: {{ default "7235" (env "MATCHING_GRPC_PORT") }}
      membershipPort: {{ default "6935" (env "MATCHING_MEMBERSHIP_PORT") }}
      bindOnIP: {{ default "127.0.0.1" (env "BIND_ON_IP") | quote }}

  history:
    rpc:
      grpcPort: {{ default "7234" (env "HISTORY_GRPC_PORT") }}
      membershipPort: {{ default "6934" (env "HISTORY_MEMBERSHIP_PORT") }}
      bindOnIP: {{ default "127.0.0.1" (env "BIND_ON_IP") | quote }}

  worker:
    rpc:
      grpcPort: {{ default "7239" (env "WORKER_GRPC_PORT") }}
      membershipPort: {{ default "6939" (env "WORKER_MEMBERSHIP_PORT") }}
      bindOnIP: {{ default "127.0.0.1" (env "BIND_ON_IP") | quote }}

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "{{ default "127.0.0.1" (env "BIND_ON_IP") }}:{{ default "7233" (env "FRONTEND_GRPC_PORT") }}"
      httpAddress: "{{ default "127.0.0.1" (env "BIND_ON_IP") }}:{{ default "7243" (env "FRONTEND_HTTP_PORT") }}"

dcRedirectionPolicy:
  policy: noop

archival:
  history:
    state: enabled
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: enabled
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "disabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "disabled"
      URI: "file:///tmp/temporal_vis_archival/development"

dynamicConfigClient:
  filepath: {{ default "config/dynamicconfig/development-sql.yaml" (env "DYNAMIC_CONFIG_FILE_PATH") | quote }}
  pollInterval: {{ default "10s" (env "DYNAMIC_CONFIG_POLL_INTERVAL") }}
